package com.erp.montfortuganda.exception;

import com.erp.montfortuganda.common.response.ApiResponse;
import jakarta.persistence.EntityNotFoundException;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.ConstraintViolationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.orm.ObjectOptimisticLockingFailureException;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.resource.NoResourceFoundException;

import java.util.HashMap;
import java.util.Map;

@ControllerAdvice
@SuppressWarnings("unused")
public class GlobalExceptionHandler {

    private static final Logger logger =
            LoggerFactory.getLogger(GlobalExceptionHandler.class);

    /*
     * Handles validation errors generated by @Valid request DTOs.
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String, Object>> handleValidationExceptions(
            MethodArgumentNotValidException exception
    ) {

        Map<String, String> fieldErrors = new HashMap<>();

        for (FieldError error :
                exception.getBindingResult().getFieldErrors()) {

            fieldErrors.put(
                    error.getField(),
                    error.getDefaultMessage()
            );
        }

        Map<String, Object> response = new HashMap<>();
        response.put("success", false);
        response.put("message", "Validation failed");
        response.put("errors", fieldErrors);

        return ResponseEntity
                .status(HttpStatus.BAD_REQUEST)
                .body(response);
    }

    /*
     * Handles Jakarta Bean Validation errors raised outside controller DTOs.
     */
    @ExceptionHandler(ConstraintViolationException.class)
    public ResponseEntity<Map<String, Object>>
    handleConstraintViolationException(
            ConstraintViolationException exception
    ) {

        Map<String, String> fieldErrors = new HashMap<>();

        for (ConstraintViolation<?> violation :
                exception.getConstraintViolations()) {

            String propertyPath =
                    violation.getPropertyPath().toString();

            String fieldName = propertyPath.contains(".")
                    ? propertyPath.substring(
                    propertyPath.lastIndexOf('.') + 1
            )
                    : propertyPath;

            fieldErrors.put(
                    fieldName,
                    violation.getMessage()
            );
        }

        Map<String, Object> response = new HashMap<>();
        response.put("success", false);
        response.put(
                "message",
                "Validation constraint violation"
        );
        response.put("errors", fieldErrors);

        return ResponseEntity
                .status(HttpStatus.BAD_REQUEST)
                .body(response);
    }
    /*
     * Handles safe business-validation failures.
     */
    @ExceptionHandler(BadRequestException.class)
    public ResponseEntity<Map<String, Object>>
    handleBadRequestException(
            BadRequestException exception
    ) {
        return buildErrorResponse(
                HttpStatus.BAD_REQUEST,
                exception.getMessage() == null
                        ? "Invalid Employee information."
                        : exception.getMessage()
        );
    }

    /*
     * Handles duplicate Employee data and records currently in use.
     */
    @ExceptionHandler({
            DuplicateResourceException.class,
            EntityInUseException.class
    })
    public ResponseEntity<Map<String, Object>>
    handleConflictException(
            RuntimeException exception
    ) {
        return buildErrorResponse(
                HttpStatus.CONFLICT,
                exception.getMessage() == null
                        ? "The submitted record already exists."
                        : exception.getMessage()
        );
    }

    /*
     * Handles application resource lookup failures.
     */
    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<Map<String, Object>>
    handleResourceNotFoundException(
            ResourceNotFoundException exception
    ) {
        return buildErrorResponse(
                HttpStatus.NOT_FOUND,
                exception.getMessage() == null
                        ? "Requested record was not found."
                        : exception.getMessage()
        );
    }

    /*
     * Handles users without an assigned branch.
     */
    @ExceptionHandler(BranchNotAssignedException.class)
    public ResponseEntity<Map<String, Object>>
    handleBranchNotAssignedException(
            BranchNotAssignedException exception
    ) {
        return buildErrorResponse(
                HttpStatus.FORBIDDEN,
                exception.getMessage() == null
                        ? "No branch is assigned to the current user."
                        : exception.getMessage()
        );
    }

    /*
     * Handles authentication failures.
     */
    @ExceptionHandler(UnauthorizedException.class)
    public ResponseEntity<Map<String, Object>>
    handleUnauthorizedException(
            UnauthorizedException exception
    ) {
        return buildErrorResponse(
                HttpStatus.UNAUTHORIZED,
                exception.getMessage() == null
                        ? "Authentication is required."
                        : exception.getMessage()
        );
    }
    /*
     * Handles records that do not exist.
     */
    @ExceptionHandler(EntityNotFoundException.class)
    public ResponseEntity<Map<String, Object>>
    handleEntityNotFoundException(
            EntityNotFoundException exception
    ) {

        return buildErrorResponse(
                HttpStatus.NOT_FOUND,
                exception.getMessage() == null
                        ? "Resource not found"
                        : exception.getMessage()
        );
    }

    /*
     * Handles invalid arguments passed to services.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<Map<String, Object>>
    handleIllegalArgumentException(
            IllegalArgumentException exception
    ) {

        return buildErrorResponse(
                HttpStatus.BAD_REQUEST,
                exception.getMessage() == null
                        ? "Invalid input"
                        : exception.getMessage()
        );
    }

    /*
     * Handles general security/access errors.
     */
    @ExceptionHandler(SecurityException.class)
    public ResponseEntity<Map<String, Object>>
    handleSecurityException(
            SecurityException exception
    ) {

        return buildErrorResponse(
                HttpStatus.FORBIDDEN,
                exception.getMessage() == null
                        ? "Access denied"
                        : exception.getMessage()
        );
    }

    /*
     * Handles branch-level access restrictions.
     */
    @ExceptionHandler(BranchAccessDeniedException.class)
    public ResponseEntity<ApiResponse<Void>>
    handleBranchAccessDenied(
            BranchAccessDeniedException exception
    ) {

        return ResponseEntity
                .status(HttpStatus.FORBIDDEN)
                .body(
                        ApiResponse.error(
                                exception.getMessage()
                        )
                );
    }

    /*
     * Keeps GoDaddy donation outages isolated from the primary ERP database.
     */
    @ExceptionHandler(
            ExternalDonationUnavailableException.class
    )
    public ResponseEntity<Map<String, Object>>
    handleExternalDonationUnavailable(
            ExternalDonationUnavailableException exception
    ) {
        logger.warn(
                "External donation database is unavailable: {}",
                exception.getCause() == null
                        ? exception.getMessage()
                        : exception.getCause().getMessage()
        );

        return buildErrorResponse(
                HttpStatus.SERVICE_UNAVAILABLE,
                "Donation information is temporarily unavailable."
        );
    }

    /*
     * Handles stale version updates.
     */
    @ExceptionHandler(
            ObjectOptimisticLockingFailureException.class
    )
    public ResponseEntity<ApiResponse<Void>>
    handleOptimisticLocking(
            ObjectOptimisticLockingFailureException exception
    ) {

        logger.warn(
                "Optimistic locking conflict: {}",
                exception.getMessage()
        );

        return ResponseEntity
                .status(HttpStatus.CONFLICT)
                .body(
                        ApiResponse.error(
                                "This record was modified by another user. "
                                        + "Refresh the page and try again."
                        )
                );
    }

    /*
     * Handles unique keys, foreign keys and other database constraints.
     */
    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ApiResponse<Void>>
    handleDataIntegrityViolation(
            DataIntegrityViolationException exception
    ) {

        logger.error(
                "Database integrity violation",
                exception
        );

        return ResponseEntity
                .status(HttpStatus.CONFLICT)
                .body(
                        ApiResponse.error(
                                "The operation violated a database constraint."
                        )
                );
    }

    /*
     * Missing static files, images, CSS and JavaScript resources.
     */
    @ExceptionHandler(NoResourceFoundException.class)
    public ResponseEntity<String>
    handleNoResourceFoundException(
            NoResourceFoundException exception
    ) {

        return ResponseEntity
                .status(HttpStatus.NOT_FOUND)
                .body("Resource not found");
    }

    /*
     * Final fallback for unexpected errors.
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<Map<String, Object>>
    handleGlobalException(
            Exception exception
    ) {

        logger.error(
                "Unhandled server exception occurred",
                exception
        );

        return buildErrorResponse(
                HttpStatus.INTERNAL_SERVER_ERROR,
                "An unexpected internal server error occurred."
        );
    }

    private ResponseEntity<Map<String, Object>>
    buildErrorResponse(
            HttpStatus status,
            String message
    ) {

        Map<String, Object> response = new HashMap<>();
        response.put("success", false);
        response.put("status", status.value());
        response.put("message", message);

        return ResponseEntity
                .status(status)
                .body(response);
    }
}
