package com.erp.montfortuganda.employee.service;

import com.erp.montfortuganda.auth.entity.CredentialDeliveryStatus;
import com.erp.montfortuganda.auth.entity.ErpRole;
import com.erp.montfortuganda.auth.entity.ErpUserRole;
import com.erp.montfortuganda.auth.entity.User;
import com.erp.montfortuganda.auth.repository.ErpRoleRepository;
import com.erp.montfortuganda.auth.repository.UserRepository;
import com.erp.montfortuganda.employee.dto.request.EmployeeAccountRequest;
import com.erp.montfortuganda.employee.dto.request.EmployeeLoginAccountRequest;
import com.erp.montfortuganda.employee.dto.response.EmployeeLoginRoleOptionResponse;
import com.erp.montfortuganda.employee.entity.ErpEmployee;
import com.erp.montfortuganda.exception.BadRequestException;
import com.erp.montfortuganda.exception.DuplicateResourceException;
import com.erp.montfortuganda.exception.ResourceNotFoundException;
import com.erp.montfortuganda.infrastructure.service.PasswordService;
import com.erp.montfortuganda.school.entity.Branch;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;

/**
 * Creates and manages login accounts linked to Employee records.
 * <p>
 * Security rules:
 * <p>
 * - usernames are generated by the backend from the Employee number;
 * - browser-supplied role IDs are resolved to active database roles;
 * - system-level administrator roles cannot be assigned to Employees;
 * - temporary passwords are generated with SecureRandom and stored only as
 *   password hashes;
 * - plain temporary passwords exist only in the returned in-memory result;
 * - temporary credentials expire after 72 hours and require first-login
 *   password change;
 * - Employee and User branch ownership must match;
 * - credential-delivery lifecycle changes are persisted without exposing the
 *   temporary password.
 */
@SuppressWarnings("unused")
@Service
public class EmployeeAccountService {

    private static final long TEMPORARY_PASSWORD_VALIDITY_HOURS =
            72L;

    /**
     * These are system-administration or non-employee portal roles. They must
     * never be assigned through Employee registration or Employee account
     * creation.
     *
     * <p>All other active roles are loaded from the role master table, so new
     * staff roles do not require Java code changes.</p>
     */
    private static final Set<String> NON_EMPLOYEE_ROLE_CODES =
            Set.of(
                    "SUPER_ADMIN",
                    "ERP_ADMIN",
                    "NGO_ADMIN",
                    "BRANCH_ADMIN",
                    "SCHOOL_ADMIN",
                    "STUDENT",
                    "PARENT",
                    "GUEST"
            );

    private final UserRepository userRepository;
    private final ErpRoleRepository roleRepository;
    private final PasswordService passwordService;

    public EmployeeAccountService(
            UserRepository userRepository,
            ErpRoleRepository roleRepository,
            PasswordService passwordService
    ) {
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.passwordService = passwordService;
    }

    /**
     * Returns active Employee-assignable roles from the role master table.
     */
    @Transactional(readOnly = true)
    public List<EmployeeLoginRoleOptionResponse> getAssignableLoginRoles() {
        return roleRepository
                .findAllByActiveTrueOrderByRoleNameAsc()
                .stream()
                .filter(Objects::nonNull)
                .filter(role ->
                        !NON_EMPLOYEE_ROLE_CODES.contains(
                                normalizeRoleCode(
                                        role.getRoleCode()
                                )
                        )
                )
                .map(role ->
                        new EmployeeLoginRoleOptionResponse(
                                role.getRoleId(),
                                normalizeRoleCode(
                                        role.getRoleCode()
                                ),
                                role.getRoleName()
                        )
                )
                .toList();
    }

    /**
     * Creates an Employee login account when requested.
     * <p>
     * This method must execute inside the same transaction that persists the
     * Employee. If later Employee registration work fails, both the account
     * and Employee changes roll back together.
     */
    @Transactional
    public AccountCreationResult createEmployeeAccount(
            EmployeeAccountRequest request,
            ErpEmployee employee,
            Integer createdByUserId
    ) {
        Objects.requireNonNull(
                request,
                "Employee account request is required."
        );
        Objects.requireNonNull(
                employee,
                "Employee entity is required."
        );

        if (!request.generateLogin()) {
            employee.setUser(null);
            employee.setLoginEnabled(false);

            return AccountCreationResult.notCreated();
        }

        return createAccount(
                employee,
                request.roleId(),
                request.sendEmail(),
                createdByUserId
        );
    }

    /**
     * Creates a login account for an existing Employee who was originally
     * registered without one.
     */
    @Transactional
    public AccountCreationResult createEmployeeAccountForExistingEmployee(
            EmployeeLoginAccountRequest request,
            ErpEmployee employee,
            Integer createdByUserId
    ) {
        Objects.requireNonNull(
                request,
                "Employee login account request is required."
        );
        Objects.requireNonNull(
                employee,
                "Employee entity is required."
        );

        return createAccount(
                employee,
                request.roleId(),
                request.sendEmail(),
                createdByUserId
        );
    }

    /**
     * Replaces the current password with a newly generated temporary password.
     *
     * <p>The previous password stops working immediately. The replacement
     * password expires after 72 hours, requires a password change at first
     * login and is returned only in this protected in-memory result so the
     * after-commit email listener can deliver it.</p>
     */
    @Transactional
    public TemporaryPasswordResetResult resetTemporaryPassword(
            ErpEmployee employee
    ) {
        Objects.requireNonNull(
                employee,
                "Employee entity is required."
        );

        validateEmployeeForAccount(employee);

        User user =
                employee.getUser();

        if (user == null) {
            throw new ResourceNotFoundException(
                    "This Employee does not have a login account."
            );
        }

        validateLinkedUser(
                employee,
                user
        );

        String temporaryPassword =
                passwordService
                        .generateSecureTemporaryPassword();

        LocalDateTime createdAt =
                LocalDateTime.now(
                        ZoneOffset.UTC
                );

        LocalDateTime expiresAt =
                createdAt.plusHours(
                        TEMPORARY_PASSWORD_VALIDITY_HOURS
                );

        user.setPassword(
                passwordService.hashPassword(
                        temporaryPassword
                )
        );
        user.setMustChangePassword(true);
        user.setTemporaryPasswordCreatedAt(createdAt);
        user.setTemporaryPasswordExpiresAt(expiresAt);
        user.setPasswordChangedAt(null);
        user.setCredentialDeliveryStatus(
                CredentialDeliveryStatus.PENDING
        );
        user.setCredentialsSentAt(null);
        user.setCredentialDeliveryAttempts(0);
        user.setCredentialVersion(
                nextCredentialVersion(
                        user.getCredentialVersion()
                )
        );

        User savedUser =
                userRepository
                        .saveAndFlush(user);

        employee.setLoginEnabled(true);

        return TemporaryPasswordResetResult.created(
                savedUser,
                temporaryPassword,
                expiresAt
        );
    }

    /**
     * Deactivates the linked User account when an Employee is deactivated.
     */
    @Transactional
    public void deactivateEmployeeAccount(
            ErpEmployee employee
    ) {
        Objects.requireNonNull(
                employee,
                "Employee entity is required."
        );

        User user =
                employee.getUser();

        if (user == null) {
            employee.setLoginEnabled(false);
            return;
        }

        user.setIsActive(0);

        userRepository.save(user);

        employee.setLoginEnabled(false);
    }

    /**
     * Records successful welcome-email delivery.
     *
     * @param resent true when this was a resend of replacement credentials
     */
    @Transactional
    public void recordCredentialDeliverySuccess(
            Integer userId,
            boolean resent
    ) {
        User user =
                requireUser(userId);

        incrementDeliveryAttempts(user);

        user.setCredentialDeliveryStatus(
                resent
                        ? CredentialDeliveryStatus.RESENT
                        : CredentialDeliveryStatus.SENT
        );

        user.setCredentialsSentAt(
                LocalDateTime.now(
                        ZoneOffset.UTC
                )
        );

        userRepository.save(user);
    }

    /**
     * Records a failed welcome-email attempt without invalidating the account
     * or deleting the generated password hash.
     */
    @Transactional
    public void recordCredentialDeliveryFailure(
            Integer userId
    ) {
        User user =
                requireUser(userId);

        incrementDeliveryAttempts(user);

        user.setCredentialDeliveryStatus(
                CredentialDeliveryStatus.FAILED
        );

        userRepository.save(user);
    }

    /**
     * Marks expired temporary credentials when an account has not completed
     * its required first password change within the validity period.
     */
    @Transactional
    public void markTemporaryCredentialsExpired(
            Integer userId
    ) {
        User user =
                requireUser(userId);

        LocalDateTime expiresAt =
                user.getTemporaryPasswordExpiresAt();

        if (
                Boolean.TRUE.equals(
                        user.getMustChangePassword()
                )
                        && expiresAt != null
                        && !expiresAt.isAfter(
                        LocalDateTime.now(
                                ZoneOffset.UTC
                        )
                )
        ) {
            user.setCredentialDeliveryStatus(
                    CredentialDeliveryStatus.EXPIRED
            );

            userRepository.save(user);
        }
    }

    /**
     * Generates the stable Employee username from the backend-generated
     * Employee number.
     */
    public String buildEmployeeUsername(
            ErpEmployee employee
    ) {
        Objects.requireNonNull(
                employee,
                "Employee entity is required."
        );

        String employeeNo =
                employee.getEmployeeNo();

        if (!StringUtils.hasText(employeeNo)) {
            throw new IllegalStateException(
                    "Employee number is required before creating a login account."
            );
        }

        String username =
                employeeNo
                        .trim()
                        .toUpperCase(
                                Locale.ROOT
                        );

        if (username.length() > 100) {
            throw new IllegalStateException(
                    "Generated Employee username exceeds 100 characters."
            );
        }

        return username;
    }

    private AccountCreationResult createAccount(
            ErpEmployee employee,
            Long roleId,
            boolean sendEmail,
            Integer createdByUserId
    ) {
        validateEmployeeForAccount(employee);

        if (employee.getUser() != null) {
            throw new DuplicateResourceException(
                    "This Employee already has a login account."
            );
        }

        ErpRole role =
                requireAssignableRole(
                        roleId
                );

        String username =
                buildEmployeeUsername(employee);

        if (userRepository.existsByUsername(username)) {
            throw new DuplicateResourceException(
                    "A user account already exists with username "
                            + username
                            + "."
            );
        }

        String temporaryPassword =
                passwordService
                        .generateSecureTemporaryPassword();

        LocalDateTime createdAt =
                LocalDateTime.now(
                        ZoneOffset.UTC
                );

        LocalDateTime expiresAt =
                createdAt.plusHours(
                        TEMPORARY_PASSWORD_VALIDITY_HOURS
                );

        User user =
                buildUser(
                        employee,
                        role,
                        username,
                        temporaryPassword,
                        createdAt,
                        expiresAt
                );

        ErpUserRole userRole =
                buildUserRole(
                        role,
                        createdByUserId
                );

        user.addRole(userRole);

        User savedUser =
                userRepository
                        .saveAndFlush(user);

        employee.setUser(savedUser);
        employee.setLoginEnabled(true);

        return AccountCreationResult.created(
                savedUser,
                role,
                temporaryPassword,
                expiresAt,
                sendEmail
        );
    }

    private User buildUser(
            ErpEmployee employee,
            ErpRole role,
            String username,
            String temporaryPassword,
            LocalDateTime createdAt,
            LocalDateTime expiresAt
    ) {
        User user =
                new User();

        user.setUsername(username);
        user.setPassword(
                passwordService.hashPassword(
                        temporaryPassword
                )
        );
        user.setRole(
                normalizeRoleCode(
                        role.getRoleCode()
                )
        );
        user.setAssignedBranch(
                employee.getBranch()
        );
        user.setIsActive(1);

        user.setMustChangePassword(true);
        user.setTemporaryPasswordCreatedAt(createdAt);
        user.setTemporaryPasswordExpiresAt(expiresAt);
        user.setPasswordChangedAt(null);

        user.setCredentialDeliveryStatus(
                CredentialDeliveryStatus.PENDING
        );
        user.setCredentialsSentAt(null);
        user.setCredentialDeliveryAttempts(0);
        user.setCredentialVersion(1);

        return user;
    }

    private ErpUserRole buildUserRole(
            ErpRole role,
            Integer createdByUserId
    ) {
        ErpUserRole userRole =
                new ErpUserRole();

        userRole.setRole(role);
        userRole.setActive(true);

        if (createdByUserId != null) {
            Long auditUserId =
                    createdByUserId.longValue();

            userRole.setCreatedBy(auditUserId);
            userRole.setUpdatedBy(auditUserId);
        }

        return userRole;
    }

    private ErpRole requireAssignableRole(
            Long roleId
    ) {
        if (roleId == null || roleId <= 0) {
            throw new BadRequestException(
                    "A valid Employee login role is required."
            );
        }

        ErpRole role =
                roleRepository
                        .findById(roleId)
                        .orElseThrow(() ->
                                new ResourceNotFoundException(
                                        "Selected Employee login role was not found."
                                )
                        );

        if (!Boolean.TRUE.equals(role.getActive())) {
            throw new BadRequestException(
                    "The selected Employee login role is inactive."
            );
        }

        String roleCode =
                normalizeRoleCode(
                        role.getRoleCode()
                );

        if (NON_EMPLOYEE_ROLE_CODES.contains(roleCode)) {
            throw new SecurityException(
                    "The selected role cannot be assigned to an Employee login account."
            );
        }

        return role;
    }

    private void validateEmployeeForAccount(
            ErpEmployee employee
    ) {
        Branch branch =
                employee.getBranch();

        if (
                branch == null
                        || branch.getBranchId() == null
                        || branch.getBranchId() <= 0
        ) {
            throw new IllegalStateException(
                    "A saved branch is required before creating an Employee account."
            );
        }

        if (!StringUtils.hasText(employee.getEmployeeNo())) {
            throw new IllegalStateException(
                    "Employee number is required before creating a login account."
            );
        }

        if (!StringUtils.hasText(employee.getOfficialEmail())) {
            throw new BadRequestException(
                    "Official email is required when Employee login creation is enabled."
            );
        }

        if (!Boolean.TRUE.equals(employee.getActive())) {
            throw new BadRequestException(
                    "A login account cannot be created for an inactive Employee."
            );
        }
    }

    private void validateLinkedUser(
            ErpEmployee employee,
            User user
    ) {
        if (!Integer.valueOf(1).equals(user.getIsActive())) {
            throw new BadRequestException(
                    "The Employee login account is inactive."
            );
        }

        Branch employeeBranch =
                employee.getBranch();

        Branch userBranch =
                user.getAssignedBranch();

        if (
                employeeBranch == null
                        || userBranch == null
                        || !Objects.equals(
                        employeeBranch.getBranchId(),
                        userBranch.getBranchId()
                )
        ) {
            throw new SecurityException(
                    "Employee and login account branch ownership do not match."
            );
        }

        if (!StringUtils.hasText(user.getUsername())) {
            throw new IllegalStateException(
                    "Employee login account has no username."
            );
        }
    }

    private int nextCredentialVersion(
            Integer currentVersion
    ) {
        if (currentVersion == null || currentVersion < 1) {
            return 1;
        }

        return Math.addExact(
                currentVersion,
                1
        );
    }

    private User requireUser(
            Integer userId
    ) {
        if (userId == null || userId <= 0) {
            throw new BadRequestException(
                    "A valid User ID is required."
            );
        }

        return userRepository
                .findById(userId)
                .orElseThrow(() ->
                        new ResourceNotFoundException(
                                "Employee login account was not found."
                        )
                );
    }

    private void incrementDeliveryAttempts(
            User user
    ) {
        Integer attempts =
                user.getCredentialDeliveryAttempts();

        user.setCredentialDeliveryAttempts(
                attempts == null
                        ? 1
                        : Math.addExact(
                        attempts,
                        1
                )
        );
    }

    private String normalizeRoleCode(
            String roleCode
    ) {
        if (!StringUtils.hasText(roleCode)) {
            throw new IllegalStateException(
                    "Selected Employee login role has no role code."
            );
        }

        return roleCode
                .trim()
                .toUpperCase(
                        Locale.ROOT
                );
    }

    /**
     * In-memory result returned to the registration workflow.
     * <p>
     * The plain temporary password must be used only by the after-commit email
     * event and must never be logged, persisted or returned through the API.
     */
    public record AccountCreationResult(
            boolean created,
            Integer userId,
            String username,
            Long roleId,
            String roleCode,
            String temporaryPassword,
            LocalDateTime temporaryPasswordExpiresAt,
            boolean sendEmail,
            CredentialDeliveryStatus credentialDeliveryStatus
    ) {

        private static AccountCreationResult notCreated() {
            return new AccountCreationResult(
                    false,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    false,
                    CredentialDeliveryStatus.NOT_REQUIRED
            );
        }

        private static AccountCreationResult created(
                User user,
                ErpRole role,
                String temporaryPassword,
                LocalDateTime expiresAt,
                boolean sendEmail
        ) {
            return new AccountCreationResult(
                    true,
                    user.getId(),
                    user.getUsername(),
                    role.getRoleId(),
                    role.getRoleCode(),
                    temporaryPassword,
                    expiresAt,
                    sendEmail,
                    user.getCredentialDeliveryStatus()
            );
        }

        /**
         * Prevents accidental temporary-password disclosure through logs.
         */
        @Override
        public String toString() {
            return "AccountCreationResult{"
                    + "created="
                    + created
                    + ", userId="
                    + userId
                    + ", username='"
                    + username
                    + '\''
                    + ", roleId="
                    + roleId
                    + ", roleCode='"
                    + roleCode
                    + '\''
                    + ", temporaryPassword='[PROTECTED]'"
                    + ", temporaryPasswordExpiresAt="
                    + temporaryPasswordExpiresAt
                    + ", sendEmail="
                    + sendEmail
                    + ", credentialDeliveryStatus="
                    + credentialDeliveryStatus
                    + '}';
        }
    }

    /**
     * Protected in-memory result for a replacement temporary password.
     */
    public record TemporaryPasswordResetResult(
            Integer userId,
            String username,
            String temporaryPassword,
            LocalDateTime temporaryPasswordExpiresAt,
            CredentialDeliveryStatus credentialDeliveryStatus
    ) {

        private static TemporaryPasswordResetResult created(
                User user,
                String temporaryPassword,
                LocalDateTime expiresAt
        ) {
            return new TemporaryPasswordResetResult(
                    user.getId(),
                    user.getUsername(),
                    temporaryPassword,
                    expiresAt,
                    user.getCredentialDeliveryStatus()
            );
        }

        /**
         * Prevents accidental temporary-password disclosure through logs.
         */
        @Override
        public String toString() {
            return "TemporaryPasswordResetResult{"
                    + "userId="
                    + userId
                    + ", username='"
                    + username
                    + '\''
                    + ", temporaryPassword='[PROTECTED]'"
                    + ", temporaryPasswordExpiresAt="
                    + temporaryPasswordExpiresAt
                    + ", credentialDeliveryStatus="
                    + credentialDeliveryStatus
                    + '}';
        }
    }
}
