$kind: http-request
name: "Test Case 4: Fetch All Submitted Applications"
url: http://localhost:8080/api/admin/applications
method: GET
headers:
  Authorization: " Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdF9raXppdG9fYWRtaW4iLCJpYXQiOjE3ODA1NTM4NjIsImV4cCI6MTc4MDY0MDI2Mn0.mUmj6-yuTD-MPPMKR-UjkKi65mBIPjP3QXTymLqQ6KI"
auth:
  type: bearer
  credentials:
    token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdF9raXppdG9fYWRtaW4iLCJpYXQiOjE3ODA1NTM4NjIsImV4cCI6MTc4MDY0MDI2Mn0.mUmj6-yuTD-MPPMKR-UjkKi65mBIPjP3QXTymLqQ6KI
order: 3016869317444243
