$kind: http-request
name: "Test Case 6: Change Application Status"
url: http://localhost:8080/api/admin/applications/status
method: POST
headers:
  Authorization: " Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdF9raXppdG9fYWRtaW4iLCJpYXQiOjE3ODA1NTM4NjIsImV4cCI6MTc4MDY0MDI2Mn0.mUmj6-yuTD-MPPMKR-UjkKi65mBIPjP3QXTymLqQ6KI"
body:
  type: urlencoded
  content:
    app_id: "6"
    status: reject
auth:
  type: bearer
  credentials:
    token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdF9raXppdG9fYWRtaW4iLCJpYXQiOjE3ODA1NTM4NjIsImV4cCI6MTc4MDY0MDI2Mn0.mUmj6-yuTD-MPPMKR-UjkKi65mBIPjP3QXTymLqQ6KI
order: 3822975593670107
