package com.erp.montfortuganda.employee.enums;

public enum EmployeeDocumentType {
    NATIONAL_ID, PASSPORT, WORK_PERMIT, ACADEMIC_CERTIFICATE,
    TRANSCRIPT, CV, APPOINTMENT_LETTER, CONTRACT, TIN_CERTIFICATE,
    MEDICAL_REPORT, POLICE_CLEARANCE, BIRTH_CERTIFICATE,
    PHOTO, SIGNATURE, OTHER
}