// File: src/main/java/com/erp/montfortuganda/employee/enums/EmployeeDocumentType.java
package com.erp.montfortuganda.employee.enums;
public enum EmployeeDocumentType {
    PASSPORT_PHOTO, SIGNATURE, RESUME, CURRICULUM_VITAE, NATIONAL_ID, PASSPORT, BIRTH_CERTIFICATE,
    MARRIAGE_CERTIFICATE, MEDICAL_CERTIFICATE, POLICE_CLEARANCE, APPOINTMENT_LETTER, EMPLOYMENT_CONTRACT,
    CONFIDENTIALITY_AGREEMENT, CODE_OF_CONDUCT_AGREEMENT, EXPERIENCE_CERTIFICATE, RELIEVING_LETTER,
    SALARY_CERTIFICATE, BANK_DOCUMENT, NSSF_DOCUMENT, TIN_CERTIFICATE, WORK_PERMIT, VISA,
    TEACHING_LICENSE, PROFESSIONAL_LICENSE, ACADEMIC_CERTIFICATE, OTHER
}