package com.erp.montfortuganda.employee.enums;

public enum EmployeeQualificationLevel {
    PRIMARY, O_LEVEL, A_LEVEL, CERTIFICATE, DIPLOMA, ADVANCED_DIPLOMA,
    BACHELOR, POST_GRADUATE, POST_GRADUATE_DIPLOMA, MASTER, M_PHIL,
    PHD, PROFESSIONAL, VOCATIONAL, SHORT_COURSE, TRAINING,
    CERTIFICATION, OTHER
}