package com.erp.montfortuganda.student.bulkimport.excel;

import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Exact header contract for the approved Student bulk-import workbook.
 *
 * <p>Branch ownership is never accepted from Excel. The authenticated
 * user's branch is supplied through ImportContext and enforced by the
 * backend while resolving references and creating the Student.</p>
 *
 * <p>The following logical values are generated by the backend and are
 * therefore not physical Excel columns:</p>
 *
 * <ul>
 *     <li>Admission Type</li>
 *     <li>Joining Date</li>
 *     <li>Preferred Contact</li>
 *     <li>Fee Responsibility</li>
 *     <li>Parents Living Together</li>
 * </ul>
 */
public final class StudentExcelHeaders {

    public static final String STUDENT_SHEET =
            "Students Import";

    public static final String REFERENCE_LISTS_SHEET =
            "Reference Lists";

    // =====================================================================
    // PHYSICAL EXCEL COLUMNS
    // =====================================================================

    public static final String ADMISSION_NO =
            "Admission No (Optional)";

    public static final String ADMISSION_YEAR =
            "Admission Year";

    public static final String FIRST_NAME =
            "First Name";

    public static final String MIDDLE_NAME =
            "Middle Name";

    public static final String LAST_NAME =
            "Last Name";

    public static final String GENDER =
            "Gender";

    public static final String DATE_OF_BIRTH =
            "Date of Birth";

    public static final String EDUCATION_LEVEL =
            "Education Level";

    public static final String CLASS_NAME =
            "Class";

    public static final String SECTION =
            "Section";

    public static final String ACADEMIC_YEAR =
            "Academic Year";

    public static final String FATHER_OR_GUARDIAN_NAME =
            "Father/Guardian Name";

    public static final String MOTHER_OR_GUARDIAN_NAME =
            "Mother/Guardian Name";

    public static final String GUARDIAN_RELATIONSHIP =
            "Guardian Relationship";

    public static final String MOBILE_NUMBER =
            "Mobile No";

    public static final String ALTERNATE_MOBILE =
            "Alternate Mobile";

    public static final String EMAIL =
            "Email";

    public static final String NATIONALITY =
            "Nationality";

    public static final String NATIONAL_ID_OR_PASSPORT =
            "National ID/Passport";

    public static final String ADDRESS_COUNTRY =
            "Address Country";

    public static final String STATE =
            "State";

    public static final String DISTRICT =
            "District";

    public static final String COUNTY =
            "County";

    public static final String SUB_COUNTY =
            "Sub County";

    public static final String PARISH =
            "Parish";

    public static final String VILLAGE =
            "Village";

    public static final String STREET =
            "Street";

    public static final String PREVIOUS_SCHOOL =
            "Previous School";

    public static final String RELIGION =
            "Religion";

    public static final String BLOOD_GROUP =
            "Blood Group";

    public static final String TRANSPORT_REQUIRED =
            "Transport Required (Yes/No)";

    public static final String HOSTEL_REQUIRED =
            "Hostel Required (Yes/No)";

    public static final String SCHOLARSHIP =
            "Scholarship (Yes/No)";

    public static final String MEDICAL_CONDITIONS =
            "Medical Conditions";

    public static final String REMARKS =
            "Remarks";

    // =====================================================================
    // LEGACY INTERNAL LABEL — NOT AN EXCEL COLUMN
    // =====================================================================

    /**
     * Retained temporarily so dependent mapper and validator files compile
     * while their row-level Branch handling is removed in the next steps.
     * This value is not included in ALL_HEADERS or any Excel metadata set.
     */
    @Deprecated(forRemoval = true)
    public static final String BRANCH =
            "Branch";

    // =====================================================================
    // BACKEND-GENERATED LOGICAL FIELDS — NOT EXCEL COLUMNS
    // =====================================================================

    public static final String ADMISSION_TYPE =
            "Admission Type";

    public static final String JOINING_DATE =
            "Joining Date";

    public static final String PREFERRED_CONTACT =
            "Preferred Contact";

    public static final String FEE_RESPONSIBILITY =
            "Fee Responsibility";

    public static final String PARENTS_LIVING_TOGETHER =
            "Parents Living Together";

    /**
     * Written only into invalid physical Excel cells in a corrected workbook.
     */
    public static final String ENTER_VALID_DATA =
            "ENTER VALID DATA";

    /**
     * Exact approved Student workbook order after removing Branch.
     *
     * <p>Total physical columns: 35. All cells are optional, while the
     * header structure remains fixed.</p>
     */
    public static final List<String> ALL_HEADERS = List.of(
            ADMISSION_NO,
            ADMISSION_YEAR,
            FIRST_NAME,
            MIDDLE_NAME,
            LAST_NAME,
            GENDER,
            DATE_OF_BIRTH,
            EDUCATION_LEVEL,
            CLASS_NAME,
            SECTION,
            ACADEMIC_YEAR,
            FATHER_OR_GUARDIAN_NAME,
            MOTHER_OR_GUARDIAN_NAME,
            GUARDIAN_RELATIONSHIP,
            MOBILE_NUMBER,
            ALTERNATE_MOBILE,
            EMAIL,
            NATIONALITY,
            NATIONAL_ID_OR_PASSPORT,
            ADDRESS_COUNTRY,
            STATE,
            DISTRICT,
            COUNTY,
            SUB_COUNTY,
            PARISH,
            VILLAGE,
            STREET,
            PREVIOUS_SCHOOL,
            RELIGION,
            BLOOD_GROUP,
            TRANSPORT_REQUIRED,
            HOSTEL_REQUIRED,
            SCHOLARSHIP,
            MEDICAL_CONDITIONS,
            REMARKS
    );

    /**
     * No Student Excel cell is mandatory.
     *
     * <p>The workbook must retain the complete 35-column header structure,
     * but individual row cells may be blank. Required database values are
     * resolved or derived by the secure backend import pipeline.</p>
     */
    public static final Set<String> REQUIRED_HEADERS = Set.of();

    public static final Set<String> DATE_HEADERS = Set.of(
            DATE_OF_BIRTH
    );

    public static final Set<String> YES_NO_HEADERS = Set.of(
            TRANSPORT_REQUIRED,
            HOSTEL_REQUIRED,
            SCHOLARSHIP
    );

    public static final Set<String> DROPDOWN_HEADERS = Set.of(
            GENDER,
            EDUCATION_LEVEL,
            CLASS_NAME,
            SECTION,
            ACADEMIC_YEAR,
            GUARDIAN_RELATIONSHIP,
            RELIGION,
            BLOOD_GROUP,
            TRANSPORT_REQUIRED,
            HOSTEL_REQUIRED,
            SCHOLARSHIP
    );

    /**
     * Physical workbook fields resolved through branch-scoped or master
     * reference data.
     */
    public static final Set<String> REFERENCE_HEADERS = Set.of(
            EDUCATION_LEVEL,
            CLASS_NAME,
            SECTION,
            ACADEMIC_YEAR,
            RELIGION
    );

    /**
     * Zero-based physical positions matching ALL_HEADERS.
     */
    public static final Map<String, Integer> COLUMN_INDEX =
            Map.ofEntries(
                    Map.entry(ADMISSION_NO, 0),
                    Map.entry(ADMISSION_YEAR, 1),
                    Map.entry(FIRST_NAME, 2),
                    Map.entry(MIDDLE_NAME, 3),
                    Map.entry(LAST_NAME, 4),
                    Map.entry(GENDER, 5),
                    Map.entry(DATE_OF_BIRTH, 6),
                    Map.entry(EDUCATION_LEVEL, 7),
                    Map.entry(CLASS_NAME, 8),
                    Map.entry(SECTION, 9),
                    Map.entry(ACADEMIC_YEAR, 10),
                    Map.entry(FATHER_OR_GUARDIAN_NAME, 11),
                    Map.entry(MOTHER_OR_GUARDIAN_NAME, 12),
                    Map.entry(GUARDIAN_RELATIONSHIP, 13),
                    Map.entry(MOBILE_NUMBER, 14),
                    Map.entry(ALTERNATE_MOBILE, 15),
                    Map.entry(EMAIL, 16),
                    Map.entry(NATIONALITY, 17),
                    Map.entry(NATIONAL_ID_OR_PASSPORT, 18),
                    Map.entry(ADDRESS_COUNTRY, 19),
                    Map.entry(STATE, 20),
                    Map.entry(DISTRICT, 21),
                    Map.entry(COUNTY, 22),
                    Map.entry(SUB_COUNTY, 23),
                    Map.entry(PARISH, 24),
                    Map.entry(VILLAGE, 25),
                    Map.entry(STREET, 26),
                    Map.entry(PREVIOUS_SCHOOL, 27),
                    Map.entry(RELIGION, 28),
                    Map.entry(BLOOD_GROUP, 29),
                    Map.entry(TRANSPORT_REQUIRED, 30),
                    Map.entry(HOSTEL_REQUIRED, 31),
                    Map.entry(SCHOLARSHIP, 32),
                    Map.entry(MEDICAL_CONDITIONS, 33),
                    Map.entry(REMARKS, 34)
            );

    public static int columnIndex(
            String header
    ) {
        Integer index = COLUMN_INDEX.get(header);

        if (index == null) {
            throw new IllegalArgumentException(
                    "Unknown Student import Excel header: "
                            + header
            );
        }

        return index;
    }

    public static boolean isRequired(
            String header
    ) {
        return REQUIRED_HEADERS.contains(header);
    }

    public static boolean isDateHeader(
            String header
    ) {
        return DATE_HEADERS.contains(header);
    }

    public static boolean isYesNoHeader(
            String header
    ) {
        return YES_NO_HEADERS.contains(header);
    }

    public static boolean isDropdownHeader(
            String header
    ) {
        return DROPDOWN_HEADERS.contains(header);
    }

    public static boolean isReferenceHeader(
            String header
    ) {
        return REFERENCE_HEADERS.contains(header);
    }

    private StudentExcelHeaders() {
        throw new IllegalStateException(
                "StudentExcelHeaders is a utility class."
        );
    }
}